import type { FigureSpec } from "./types";

/*
  Figure registry — the lookup behind the `::figure id="…"` tokens in article
  bodies. One entry per in-article diagram, keyed by a stable id (convention:
  the article slug plus a short suffix, e.g. "2026-…-two-regime").

  Authoring a figure is two steps: add a typed spec here, then drop the matching
  token on its own line where the diagram should appear in the markdown. Specs
  live in TypeScript (not the markdown) so they stay type-checked and on-brand,
  and so the markdown remains clean and CMS-portable later.

  Pilot figures below were generated by the insights-engine production run.
*/

export const figuresById: Record<string, FigureSpec> = {
  "2026-opportunity-zones-notice-2026-40-transition-two-regime": {
    "type": "two-regime",
    "kicker": "QOZ TRANSITION",
    "title": "Notice 2026-40 splits QOZ investments by a single date: when the qualifying investment was made.",
    "pivot": {
      "date": "Dec 31, 2026",
      "label": "Date the qualifying investment is made"
    },
    "left": {
      "heading": "Legacy regime — invested on or before Dec 31, 2026",
      "rows": [
        {
          "label": "Deferred-gain inclusion",
          "value": "Mandatory in the taxable year that includes Dec 31, 2026; cannot be re-deferred (prior § 1400Z-2(b)(1)(B))"
        },
        {
          "label": "5-year basis step-up",
          "value": "None — the new step-ups do not apply to pre-2027 money"
        },
        {
          "label": "Back-end exclusion",
          "value": "§ 1400Z-2(c) FMV step-up still available at a 10-year hold if disposed before Jan 1, 2048"
        },
        {
          "label": "Tracts",
          "value": "Old zones expire Dec 31, 2027 (Puerto Rico) / Dec 31, 2028 (all others); post-2026 property generally not QOZBP except two safe harbors"
        }
      ]
    },
    "right": {
      "heading": "New regime — invested on or after Jan 1, 2027",
      "rows": [
        {
          "label": "Deferred-gain inclusion",
          "value": "Rolling — earliest of sale, inclusion event, or 5 years from the investment date (OBBBA § 70421(c))"
        },
        {
          "label": "5-year basis step-up",
          "value": "10% of deferred gain; 30% for a qualified rural opportunity fund (§ 1400Z-2(b)(2)(B)-(C))"
        },
        {
          "label": "Back-end exclusion",
          "value": "FMV mark at a 10-year hold, capped at 30 years after the investment"
        },
        {
          "label": "Tracts",
          "value": "New designation period runs Jan 1, 2027 - Dec 31, 2036 (§ 1400Z-1(e)); nominations per Rev. Proc. 2026-14"
        }
      ]
    },
    "caption": "Two regimes now run in parallel; the date a qualifying investment is made decides which rules govern the dollars.",
    "source": "IRS Notice 2026-40 (June 2026), §§ 3-5; IRC §§ 1400Z-1, 1400Z-2 as amended by Pub. L. 119-21, § 70421."
  },
  "2026-conservation-easement-settlement-window-ir-2026-65-timeline": {
    "type": "timeline",
    "kicker": "IR-2026-65 SETTLEMENT WINDOWS",
    "title": "The penalty rate climbs on a fixed clock: 10%, then 20%, then the offer is gone.",
    "milestones": [
      {
        "date": "Day 0",
        "label": "Settlement letter issues",
        "detail": "The clock starts from each case's letter — not the May 13, 2026 announcement. Calendar every letter independently."
      },
      {
        "date": "Days 1–90",
        "label": "First window — 10% penalty",
        "value": "10%",
        "fill": 0.25,
        "detail": "Accept and pay a 10% § 6662(h) gross valuation misstatement penalty. Charitable deduction conceded; an \"other deduction\" for approximate out-of-pocket costs substituted.",
        "emphasis": true
      },
      {
        "date": "Days 91–135",
        "label": "Final window — 20% penalty",
        "value": "20%",
        "fill": 0.5,
        "detail": "Same terms, but the penalty doubles to 20%. No extension of either period will be granted."
      },
      {
        "date": "After Day 135",
        "label": "Offer withdrawn — hazards of litigation",
        "value": "~40%",
        "fill": 1,
        "detail": "Case proceeds on the merits: ~6% average allowed deduction and a 40% penalty on the Tax Court record, plus accruing interest. No third bite."
      }
    ],
    "caption": "Two consecutive, non-extendable windows run from each settlement letter; declining reverts to a 40% penalty against a ~6% allowance record.",
    "source": "IRS News Release IR-2026-65 (May 13, 2026); I.R.C. § 6662(h)."
  },
  "2026-liberty-global-economic-substance-ma-decision-path": {
    "type": "decision-path",
    "kicker": "SECTION 7701(o) SCREEN",
    "title": "Test the integrated transaction, not the favorable step: both prongs must hold, or the strict-liability penalty attaches.",
    "question": "Viewed as a whole, does the integrated transaction (a) change the taxpayer's economic position in a meaningful way apart from tax AND (b) have a substantial non-tax purpose? (§ 7701(o)(1)(A), (B))",
    "branches": [
      {
        "condition": "Both prongs satisfied on the integrated facts",
        "outcome": "Economic substance respected. Retain contemporaneous pre-tax modeling and a whole-structure business-purpose memo at deal time.",
        "tone": "go"
      },
      {
        "condition": "A prong fails, but the relevant facts are adequately disclosed on the return (§ 6662(i))",
        "outcome": "Benefit disallowed under § 7701(o); mandatory 20% accuracy penalty (§ 6662(b)(6)). No reasonable-cause defense (§ 6664(c)(2)); an opinion cannot cure it.",
        "tone": "caution"
      },
      {
        "condition": "A prong fails and the transaction is not adequately disclosed",
        "outcome": "Disallowance plus a 40% penalty (§ 6662(i)), still with no reasonable-cause escape. Redesign or disclose before closing.",
        "tone": "stop"
      }
    ],
    "caption": "The unit of analysis is the entire series (§ 7701(o)(5)(D)) — not the step that produces the deduction; ordinary building blocks (Section 351, check-the-box) inside the plan do not exempt it.",
    "source": "Liberty Global, Inc. v. United States, No. 23-1410 (10th Cir. Apr. 21, 2026); 26 U.S.C. §§ 7701(o)(1), (5)(D), 6662(b)(6), (i), 6664(c)(2)."
  },
};

export function getFigure(id: string): FigureSpec | undefined {
  return figuresById[id];
}
